name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -Ur requirements.dev.txt
    - name: Install the library
      run: python3 setup.py install
    - name: Run tests
      run: python -m pytest
